// <auto-generated />
using System;
using JAP_Task_1_MoviesApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace JAP_Task_1_MoviesApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210901225656_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("JAP_Task_1_MoviesApi.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<double>("VoteAverage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Overview = "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
                            PosterPath = "/iXbWpCkIauBMStSTUT9v4GXvdgH.jpg",
                            ReleaseDate = new DateTime(2021, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Suicide Squad",
                            VoteAverage = 8.0
                        },
                        new
                        {
                            Id = 2,
                            Overview = "A devastated husband vows to bring justice to the people responsible for his wife's death while protecting the only family he has left, his daughter.",
                            PosterPath = "/cP7odDzzFBD9ycxj2laTeFWGLjD.jpg",
                            ReleaseDate = new DateTime(2021, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sweet Girl",
                            VoteAverage = 7.0
                        },
                        new
                        {
                            Id = 3,
                            Overview = "Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his dilapidated boat. Together, they search for an ancient tree that holds the power to heal – a discovery that will change the future of medicine.",
                            PosterPath = "/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg",
                            ReleaseDate = new DateTime(2021, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jungle Cruise",
                            VoteAverage = 7.9000000000000004
                        },
                        new
                        {
                            Id = 4,
                            Overview = "Ryder and the pups are called to Adventure City to stop Mayor Humdinger from turning the bustling metropolis into a state of chaos.",
                            PosterPath = "/ic0intvXZSfBlYPIvWXpU1ivUCO.jpg",
                            ReleaseDate = new DateTime(2021, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "PAW Patrol: The Movie",
                            VoteAverage = 8.0999999999999996
                        },
                        new
                        {
                            Id = 5,
                            Overview = "A rooster and his fowl partner embark on a dangerous trip to the Congo to recover their stolen eggs from a group of Russian goons.",
                            PosterPath = "/wrlQnKHLCBheXMNWotyr5cVDqNM.jpg",
                            ReleaseDate = new DateTime(2021, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Eggs Run",
                            VoteAverage = 8.4000000000000004
                        },
                        new
                        {
                            Id = 6,
                            Overview = "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
                            PosterPath = "/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
                            ReleaseDate = new DateTime(2021, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Black Widow",
                            VoteAverage = 7.7999999999999998
                        },
                        new
                        {
                            Id = 7,
                            Overview = "When LeBron and his young son Dom are trapped in a digital space by a rogue A.I., LeBron must get them home safe by leading Bugs, Lola Bunny and the whole gang of notoriously undisciplined Looney Tunes to victory over the A.I.'s digitized champions on the court. It's Tunes versus Goons in the highest-stakes challenge of his life.",
                            PosterPath = "/5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg",
                            ReleaseDate = new DateTime(2021, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Space Jam: A New Legacy",
                            VoteAverage = 7.5
                        },
                        new
                        {
                            Id = 8,
                            Overview = "A man will become a criminal to save his family.  Director: Shawn Welling  Writer: Derek H. Potts  Stars: Tom Vera, Tom Sizemore, Lee Majors |",
                            PosterPath = "/7p0O4mKYLIhU2E5Zcq9Z3vOZ4e9.jpg",
                            ReleaseDate = new DateTime(2021, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Narco Sub",
                            VoteAverage = 7.0999999999999996
                        },
                        new
                        {
                            Id = 9,
                            Overview = "A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.",
                            PosterPath = "/hEqw9swA8gFJuNjgWYEypwZfkZg.jpg",
                            ReleaseDate = new DateTime(2021, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Free Guy",
                            VoteAverage = 7.7999999999999998
                        },
                        new
                        {
                            Id = 10,
                            Overview = "Evan McCauley has skills he never learned and memories of places he has never visited. Self-medicated and on the brink of a mental breakdown, a secret group that call themselves “Infinites” come to his rescue, revealing that his memories are real.",
                            PosterPath = "/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg",
                            ReleaseDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Infinite",
                            VoteAverage = 7.5
                        });
                });

            modelBuilder.Entity("JAP_Task_1_MoviesApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
